name: Nuget Release

on: push
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
    - name: Build
      run: dotnet build SmartOptions/SmartOptions.csproj -c Release

    - name: Pack nugets
      run: dotnet pack SmartOptions/SmartOptions.csproj -c Release --no-build --output -s SmartOptions  .
    - name: Push to NuGet
      run: dotnet nuget push "SmartOptions/bin/Release/*.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json
